In [1]:
import numpy as np

In [25]:
#1a
print(np.arange(1, 10+1))          
print()
#1b
print(np.arange(0.5, 5, 0.25))

[ 1  2  3  4  5  6  7  8  9 10]

[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75]


In [26]:
#2a
print(np.zeros(10, dtype = int))
print()
#2b
print(np.zeros((4, 3), dtype = int))

[0 0 0 0 0 0 0 0 0 0]

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
#3a
print(np.linspace(2, 12, 5, dtype=int))
print()
#3b
print(np.linspace(3, 9, 4, dtype=int))

[ 2  4  7  9 12]

[3 5 7 9]


In [30]:
#4a
random_array = np.random.uniform(0, 0.999, (2, 4))
print(random_array)

print()
#4b
random_array_2 = np.random.uniform(10, 20, (3, 3))
print(random_array_2)

[[0.73220118 0.48605189 0.29267364 0.602247  ]
 [0.67978269 0.25371442 0.7953569  0.05909754]]

[[17.23223225 14.82740728 13.86857767]
 [15.82345868 18.46811035 11.72302973]
 [18.63470792 13.77373293 19.62987204]]


In [31]:
reshaped_array = random_array.reshape(8, 1)
print(reshaped_array)

# שסך הכל האיברים צריך להיות תואם reshape צריך לשים לב שמשתמשים בפעולת 
# כלומר אם בהתחלה הסדר היה 2 על 4 שסהכ 8 איברים אז בעת שינוי צריך שהסדר יהיה תואם למספר האיברים

[[0.73220118]
 [0.48605189]
 [0.29267364]
 [0.602247  ]
 [0.67978269]
 [0.25371442]
 [0.7953569 ]
 [0.05909754]]


In [ ]:
#5
# תוך שימוש ב נקבל תמיד את אותם מספרים האקראיים בכל הרצה, וזה עוזר לשחזור וניסויים.  seed   